### ISSUE TITLE
[LOC] "演算子 new" needs to be replaced with "new 演算子"

### ISSUE THREAD

**Issue by hyoshioka0128** [dotnet/docs.ja-jp#1192]
https://docs.microsoft.com/ja-jp/dotnet/csharp/language-reference/language-specification/introduction

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 362f3e73-a902-45e6-382d-328a4552a235
* Version Independent ID: d4253465-4bfc-e473-f745-0d5e1ff4e76c
* Content: [概要Introduction - C# language specification](https://docs.microsoft.com/ja-jp/dotnet/csharp/language-reference/language-specification/introduction)
* Content Source: [spec/introduction.md](https://github.com/dotnet/csharplang.ja-jp/blob/61761fcfe797043db13d94a7dce2b7af22dc8d9b/spec/introduction.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @hyoshioka0128
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @hyoshioka0128, 

Thank you for your linguistic feedback.  

Unfortunately, after reviewing your feedback our linguistic team considered it to be not fully aligned with our criteria for acceptance because Already fixed 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.  

Kind regards, 
Microsoft DOCS International Team
