### ISSUE TITLE
 TOC for Windows Forms ja-jp document is not translated.

### ISSUE THREAD

**Issue by hyoshioka0128** [dotnet/docs.ja-jp#594]
https://docs.microsoft.com/ja-jp/dotnet/framework/winforms/

**Comment by CeciAc** [comment]
Hello, @hyoshioka0128 
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?

**I cannot repro your issue, the TOC is localized on my end:**
![imagen](https://user-images.githubusercontent.com/26746247/55254958-0bbb9600-5238-11e9-804c-cdada95940c6.png)

 Kind regards,
Microsoft DOCS International Team

**Comment by hyoshioka0128** [comment]
@CeciAc Thanks. (I am Poor English.)
#594 is misunderstanding 
Close #594

However, #597 Reproduced.
![190330_Edge](https://user-images.githubusercontent.com/40815708/55275057-a9d85a80-5323-11e9-984b-24ecc80203d1.png)

**Comment by CeciAc** [comment]
Thanks for the clarification,  @hyoshioka0128 
We are working on it, thanks for closing this one

Kind regards
Microsoft DOCS International Team
