### ISSUE TITLE
Showing " [!INCLUDE[ndptecgdiplus](../../../../includes/ndptecgdiplus-md.md)] "

### ISSUE THREAD

**Issue by hyoshioka0128** [dotnet/docs.ja-jp#646]
https://docs.microsoft.com/ja-jp/dotnet/framework/winforms/advanced/images-bitmaps-and-metafiles

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 0a8e2b2f-cbaf-9ca5-9343-b1b45da1f6ab
* Version Independent ID: 7502ae3b-14e9-f95e-ba3a-481c4b6b453e
* Content: [イメージ、ビットマップ、およびメタファイル](https://docs.microsoft.com/ja-jp/dotnet/framework/winforms/advanced/images-bitmaps-and-metafiles)
* Content Source: [docs/framework/winforms/advanced/images-bitmaps-and-metafiles.md](https://github.com/dotnet/docs.ja-jp/blob/live/docs/framework/winforms/advanced/images-bitmaps-and-metafiles.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hello, @hyoshioka0128 

Your contribution is much appreciated. Our team reviewed your feedback and it appears that this issue has been already logged.
Please review issue # https://github.com/dotnet/docs.ja-jp/issues/645  For this reason, we are closing this issue since it is duplicated.

Kind regards,
Microsoft DOCS International Team
