### ISSUE TITLE
Extra "A" comes before the keyword when machine translated

### ISSUE THREAD

**Issue by nogic1008** [dotnet/docs.ja-jp#710]
```markdown
A `keyword` is...
```

When I write as above in English, it is machine translated with an extra "A" article as below in Japanese.

```markdown
A `keyword`は...
```
----------
For example, `Module` statement articles,
- [en-us](https://github.com/dotnet/docs/blob/live/docs/visual-basic/language-reference/statements/module-statement.md)
- [ja-jp](https://github.com/dotnet/docs.ja-jp/blob/live/docs/visual-basic/language-reference/statements/module-statement.md#L57)

```markdown
A `Module` statement defines...
```
should be translated as below

```markdown
`Module`ステートメントは...
```
but actual is

```markdown
A`Module`ステートメントは...
```

Because "A" is a common character, I did not look for other articles with this problem.

**Comment by CeciAc** [comment]
Hello, @nogic1008 
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
**Can you please provide the URL where you found this issue?**
Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @nogic1008 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Hello, @nogic1008 , 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them.

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
